{
 "title": "dash-catalogo-api",
 "description": "Saúde da catalogo-api",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL REQUESTS/SEC",
   "type": "stat",
   "description": "Total requests per second",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_gonic_request_duration_count{application=\"$application\", path!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "Number of 500 errors in last minute",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_gonic_requests_total{application=\"$application\", path!=\"/metrics\", code=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WIP: LATENCY AVERAGE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum(rate(gin_gonic_request_duration_bucket{application=\"catalogo-api\", path!=\"/metrics\"}[1m])) by (le)))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, (sum(rate(gin_gonic_request_duration_bucket{application=\"catalogo-api\", path!=\"/metrics\"}[1m])) by (le)))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, (sum(rate(gin_gonic_request_duration_bucket{application=\"catalogo-api\", path!=\"/metrics\"}[1m])) by (le)))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, (sum(rate(gin_gonic_request_duration_bucket{application=\"catalogo-api\", path!=\"/metrics\"}[1m])) by (le)))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, (sum(rate(gin_gonic_request_duration_bucket{application=\"catalogo-api\", path!=\"/metrics\"}[1m])) by (le)))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "description": "Error Rate in last 5 minutes",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(gin_gonic_requests_total{application=\"$application\", path!=\"/metrics\", code=\"500\"}[5m])) / sum(rate(gin_gonic_requests_total{application=\"$application\", path!=\"/metrics\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(gin_gonic_requests_total{application=\"$application\", path!=\"/metrics\", code=\"400\"}[5m])) / sum(rate(gin_gonic_requests_total{application=\"$application\", path!=\"/metrics\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(gin_gonic_requests_total{application=\"$application\", path!=\"/metrics\", code=\"404\"}[5m])) / sum(rate(gin_gonic_requests_total{application=\"$application\", path!=\"/metrics\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "Means latency in last minute",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gin_gonic_request_duration_sum{application=\"catalogo-api\", path!=\"/metrics\"}[5m])",
     "legendFormat": "{{path}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "description": "Requests number per endoint in last minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(gin_gonic_request_duration_sum{application=\"$application\", path=\"/v1/addresses\"}[1m]))",
     "legendFormat": "/v1/addresses"
    },
    {
     "expr": "sum(increase(gin_gonic_request_duration_sum{application=\"$application\", path=\"/v1/addresses/:address_id\"}[1m]))",
     "legendFormat": "/v1/addresses/:address_id"
    },
    {
     "expr": "sum(increase(gin_gonic_request_duration_sum{application=\"$application\", path=\"/v1/addresses/:address_id/cinemas\"}[1m]))",
     "legendFormat": "/v1/addresses/:address_id/cinemas"
    },
    {
     "expr": "sum(increase(gin_gonic_request_duration_sum{application=\"$application\", path=\"/v1/cinemas/:cinema_id\"}[1m]))",
     "legendFormat": "/v1/cinemas/:cinema_id"
    },
    {
     "expr": "sum(increase(gin_gonic_request_duration_sum{application=\"$application\", path=\"/v1/movies\"}[1m]))",
     "legendFormat": "/v1/movies"
    },
    {
     "expr": "sum(increase(gin_gonic_request_duration_sum{application=\"$application\", path=\"/v1/movies/:movie_id/posters/:poster_id\"}[1m]))",
     "legendFormat": "/v1/movies/:movie_id/posters/:poster_id"
    }
   ]
  },
  { "title": "API BASICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "START TIME",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOG",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(log_events_total{application=\"$application\", level=\"info\"}[5m]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(increase(log_events_total{application=\"$application\", level=\"warning\"}[5m]))",
     "legendFormat": "warning"
    },
    {
     "expr": "sum(increase(log_events_total{application=\"$application\", level=\"error\"}[5m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "DB CONNECTION STATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gorm_dbstats_in_use{application=\"$application\"}",
     "legendFormat": "In Use"
    },
    {
     "expr": "gorm_dbstats_idle{application=\"$application\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "gorm_dbstats_wait_count{application=\"$application\"}",
     "legendFormat": "Pending"
    }
   ]
  }
 ]
}