// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/movies": {
            "get": {
                "description": "Retrieve List all Movies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Retrieve Movie List",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.MovieListResult"
                        }
                    }
                }
            },
            "post": {
                "description": "Create List of Movies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Create Movies",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/requests.Movie"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.MovieListResult"
                        }
                    }
                }
            }
        },
        "/movies/{movieId}": {
            "get": {
                "description": "Retrieve one Movie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Retrieve Movie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the movie",
                        "name": "movieId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Movie"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "requests.Movie": {
            "type": "object",
            "required": [
                "age_rating",
                "description",
                "name",
                "subtitled"
            ],
            "properties": {
                "age_rating": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "poster": {
                    "type": "string"
                },
                "subtitled": {
                    "type": "boolean"
                }
            }
        },
        "responses.HATEOASLink": {
            "type": "object",
            "properties": {
                "href": {
                    "type": "string"
                }
            }
        },
        "responses.HATEOASMovieAndPostersList": {
            "type": "object",
            "properties": {
                "movies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.MovieListItem"
                    }
                },
                "posters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.HATEOASPosterLinks"
                    }
                }
            }
        },
        "responses.HATEOASMovieItemLinks": {
            "type": "object",
            "properties": {
                "self": {
                    "$ref": "#/definitions/responses.HATEOASLink"
                },
                "update-movie": {
                    "$ref": "#/definitions/responses.HATEOASLink"
                }
            }
        },
        "responses.HATEOASMovieListLinks": {
            "type": "object",
            "properties": {
                "create-movies": {
                    "$ref": "#/definitions/responses.HATEOASLink"
                },
                "self": {
                    "$ref": "#/definitions/responses.HATEOASLink"
                }
            }
        },
        "responses.HATEOASPosterItem": {
            "type": "object",
            "properties": {
                "poster": {
                    "$ref": "#/definitions/responses.HATEOASPosterItemLinks"
                }
            }
        },
        "responses.HATEOASPosterItemLinks": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/responses.HATEOASPosterLinks"
                }
            }
        },
        "responses.HATEOASPosterLinks": {
            "type": "object",
            "properties": {
                "delete-poster": {
                    "$ref": "#/definitions/responses.HATEOASLink"
                },
                "image": {
                    "$ref": "#/definitions/responses.HATEOASLink"
                },
                "self": {
                    "$ref": "#/definitions/responses.HATEOASLink"
                },
                "update-poster": {
                    "$ref": "#/definitions/responses.HATEOASLink"
                }
            }
        },
        "responses.Movie": {
            "type": "object",
            "properties": {
                "_embedded": {
                    "$ref": "#/definitions/responses.HATEOASPosterItem"
                },
                "_templates": {},
                "age_rating": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "subtitled": {
                    "type": "boolean"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "responses.MovieListItem": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/responses.HATEOASMovieItemLinks"
                },
                "age_rating": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "subtitled": {
                    "type": "boolean"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "responses.MovieListResult": {
            "type": "object",
            "properties": {
                "_embedded": {
                    "$ref": "#/definitions/responses.HATEOASMovieAndPostersList"
                },
                "_links": {
                    "$ref": "#/definitions/responses.HATEOASMovieListLinks"
                },
                "_templates": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
